/*
Program Name: EECS 348 Assignment 6
Description: Brute force Puzzle Solving Program
Inputs: Test file labeled Assignment6_Test_File.txt
Output: Solved Puzzle

Collaborators: Code generated by Deepseek AI, Annotated and Dubugged by Author

Author: Aiman Boullaouz
Creation Date: 3/25/20225
*/